import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const { applyReleaseSigning } = require('./with-release-signing.js') as {
  applyReleaseSigning: (gradle: string) => string
}

/**
 * The transform that makes a release APK installable.
 *
 * Without it, Expo's template points the release build type at the *debug*
 * signing config, the release workflow strips that signature, and the published
 * APK is one Android refuses to install. That failure is invisible until someone
 * downloads it, so it is pinned here instead.
 *
 * The fixture is the real generated `android/app/build.gradle` when one exists
 * on the machine, and a copy of the template's shape otherwise — `android/` is
 * regenerated by prebuild and absent on a clean checkout.
 */
const GENERATED = 'android/app/build.gradle'

const TEMPLATE_SHAPE = `android {
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.debug
        }
    }
}
`

const gradle = existsSync(GENERATED) ? readFileSync(GENERATED, 'utf8') : TEMPLATE_SHAPE

describe('release signing', () => {
  const patched = applyReleaseSigning(gradle)

  it('gives the release build type its own signing config', () => {
    expect(patched).toContain('signingConfig signingConfigs.release')
  })

  it('reads the keystore from the environment, never from the file', () => {
    expect(patched).toContain('storeFile file(System.getenv("LUME_ANDROID_KEYSTORE"))')
    // The only literal passwords left are the debug ones Expo ships.
    expect(patched.match(/storePassword '/g) ?? []).toHaveLength(1)
  })

  it('leaves the debug build type alone', () => {
    expect(patched.split('signingConfig signingConfigs.debug')).toHaveLength(2)
  })

  it('refuses to run against a template it does not recognise', () => {
    // The guard has to fail rather than skip: a template change that silently
    // produced a debug-signed release is the whole failure being prevented.
    expect(() => applyReleaseSigning('android { buildTypes { release { } } }')).toThrow(
      /signingConfigs/
    )
  })

  it('refuses when the debug reference count is not what it expects', () => {
    const odd = gradle.replace('signingConfig signingConfigs.debug', '// removed')
    expect(() => applyReleaseSigning(odd)).toThrow(/found 1/)
  })
})
